### ISSUE TITLE
When we implement New Data Structure, should we explain it in Korean or English?

### ISSUE THREAD

**Issue by Jaehun98** [18-1-SKKU-OSS/2018-1-OSS-E2#21]
I think if we implement new data structure such as 2-3 Tree, we should explain the code with comment.
Then should we write the comments in English or Korean or both of them?

**Comment by jyooj08** [comment]
I think we should write in both because we are writing a comment for Koreans, but other countries may see our comments

**Comment by hsh0130** [comment]
But If we see the  many other open sources about the data structure, their comments are almost written by English. Therefore to ensure our originality, i think Korean is better

**Comment by Goodbam** [comment]
I absolutely agree with jyoo098. Because we already gave a lot from opensource, we cannot forget the grace. And we are obliged to keep this! Therefore, we'd better use both!

**Comment by MOOK2** [comment]
English seems better
