### ISSUE TITLE
How can I improve codes better?

### ISSUE THREAD

**Issue by jyooj08** [18-1-SKKU-OSS/2018-1-OSS-E2#24]
I modify codes by improving readability or adding annotations.
Is there another way?

**Comment by Goodbam** [comment]
Umm...that's difficult question. I know what you mean. But this is for Edu. That is, all about contents is already decided. We don't need to improve the algorithm!
But keep going! We can do better than yesterday! Sleep tight~

**Comment by MOOK2** [comment]
That seems enough

**Comment by Jaehun98** [comment]
I don't know how to improve, but I think if we make codes with different ways (for example, the way using lists and the way using arrays) it would be better to understand.

**Comment by hsh0130** [comment]
How about specify the name of function or variables? ex) int find(arg1,arg2) -> int findIndex(arg1,arg2)
