### ISSUE TITLE
We need to unify the style of code

### ISSUE THREAD

**Issue by Goodbam** [18-1-SKKU-OSS/2018-1-OSS-E2#3]
Our teammates would survey what kinds of conding styles in software world!

**Comment by Goodbam** [comment]
if(a == 1) {
    for (i = 0;i < 1000;i++) {
        if (b == 10) {
            처리();
        } else if(c == 10) {
            처리();
        }
    }
}

**Comment by MOOK2** [comment]
God BSD

**Comment by Jaehun98** [comment]
I prefer K&R

**Comment by Goodbam** [comment]
Oh, I don't know everyone has own taste. But we need to unify it as i told you guys. The others would answer on this issue until today evening!

**Comment by jyooj08** [comment]
I think K&R is easier to see.
