### ISSUE TITLE
I want to add some contents to our static page

### ISSUE THREAD

**Issue by MOOK2** [18-1-SKKU-OSS/2018-1-OSS-E2#33]
Is there any idea?

**Comment by Jaehun98** [comment]
Our member's profile? I think.

**Comment by jyooj08** [comment]
It would be nice to post a URL link to our project and a description of the project additionally.

**Comment by Goodbam** [comment]
How about our plan? That is, we show people our next project, our next plan...etc...
For example, we are intrested in Deep - learning. So we are surveying like AlphaGo and
we will fork about watson~~~`
