### ISSUE TITLE
Why there are only three contributors in our OSS page?

### ISSUE THREAD

**Issue by hsh0130** [18-1-SKKU-OSS/2018-1-OSS-E2#36]

**Comment by MOOK2** [comment]
I don't know why but we can check out contributions at insights-pulse

**Comment by jyooj08** [comment]
We should check e-mail address of git

**Comment by Jaehun98** [comment]
I think because of Email or something else

**Comment by Goodbam** [comment]
Yeah,  you must see this!
[https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/](url)
be careful when inputting your email! Your Achievements will be not acknowledged!

**Comment by MOOK2** [comment]
some problems on git emails, after changing git email you should merge your branch
